version: '3.8'

services:
  frontend:
    # build: 
    #   context: .
    #   dockerfile: frontend/Dockerfile
    image: mcr.microsoft.com/devcontainers/javascript-node:0-18
    volumes:
      - .:/workspaces:cached
    command: sleep infinity
    env_file: frontend/.env
    networks:
      - shared-network
    ports:
      - "3000:3000"
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    env_file: backend/.env
    networks:
      - shared-network
    ports:
      - "9527:9527"
networks:
  shared-network:
    driver: bridge